# Generated by Django 5.1.3 on 2024-11-09 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsite',
            name='available_dates',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
