# Generated by Django 5.1.3 on 2024-11-11 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campsite',
            name='location',
        ),
        migrations.AddField(
            model_name='campsite',
            name='available_dates',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='campsite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campsite_images/'),
        ),
    ]
