# Generated by Django 5.1.3 on 2024-11-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_campsiteimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='include_meals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
