# Generated by Django 5.1.3 on 2024-11-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_include_meals_booking_special_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsite',
            name='marker_latitude',
            field=models.FloatField(default=0.0, verbose_name='Широта маркера'),
        ),
        migrations.AddField(
            model_name='campsite',
            name='marker_longitude',
            field=models.FloatField(default=0.0, verbose_name='Долгота маркера'),
        ),
    ]
